spring:
  application:
    name: frappe-metadata-server
  rsocket:
    server:
      port: 8090
  data:
    cassandra:
      keyspace-name: metadata
      local-datacenter: datacenter1
  cloud:
    consul:
      enabled: true
      discovery:
        instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}
        metadata:
          rsocket-port: ${spring.rsocket.server.port}

server:
  port: 8080