spring:
  application:
    name: frappe-metadata-server
  rsocket:
    server:
      port: 8090
  data:
    cassandra:
      keyspace-name: metadata
      local-datacenter: datacenter1

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${cachedrandom.instanceId.value}
    metadataMap:
      rSocketPort: ${spring.rsocket.server.port}
      rSocketTransport: TCP