spring:
  application:
    name: frappe-rest-server

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.application.name}:${cachedrandom.instanceId.value}