spring:
  application:
    name: frappe-rest-server
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        instanceId: ${spring.application.name}:${random.value}

server:
  port: 0