name: Java CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master, release/** ]

jobs:
  run-test:
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        java: [ '8', '11' ]
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v2
        with:
          java-version: ${{ matrix.java }}
          distribution: temurin
          cache: maven
      - name: Test with Maven
        run: mvn test